import Head from "next/head";
import Image from "next/image";

const news = [
  { name: "1", href: "#", current: false },
  { name: "2", href: "#", current: false },
  { name: "3", href: "#", current: false },
  { name: "4", href: "#", current: false },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Kempinski Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed xl:-top-4">
        <video
          loop
          autoPlay
          muted
          className=" min-h-full  min-w-full w-auto h-auto -z-10 inset-0"
        >
          <source
            src="https://baansindhorn.com/video-sdk/SDK-Stay-Classy-th.mp4"
            type="video/mp4"
          />
        </video>
      </div>
      <div className="relative  min-h-full  min-w-full w-auto h-auto pt-[50%] xl:pt-[30%]">
        <div className="bg-[#010F2A]  p-8 ">
          <div className="relative flex overflow-x-hidden text-white">
            <div className="py-12 animate-marquee whitespace-nowrap">
              <span className="text-4xl mx-4">Marquee Item 1</span>
              <span className="text-4xl mx-4">Marquee Item 2</span>
              <span className="text-4xl mx-4">Marquee Item 3</span>
              <span className="text-4xl mx-4">Marquee Item 4</span>
              <span className="text-4xl mx-4">Marquee Item 5</span>
            </div>

            <div className="absolute top-0 py-12 animate-marquee2 whitespace-nowrap">
              <span className="text-4xl mx-4">Marquee Item 1</span>
              <span className="text-4xl mx-4">Marquee Item 2</span>
              <span className="text-4xl mx-4">Marquee Item 3</span>
              <span className="text-4xl mx-4">Marquee Item 4</span>
              <span className="text-4xl mx-4">Marquee Item 5</span>
            </div>
          </div>
        </div>
        <div className="bg-red-500 m-4  p-4 ">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
          voluptate minus. Repellendus totam, reiciendis ipsa, praesentium iusto
          ipsam officia maiores aspernatur at explicabo placeat atque labore
          perspiciatis odio magni fugit fugiat expedita alias veritatis
          laboriosam. Excepturi fuga velit veniam sunt at? Unde beatae
          voluptatem nulla similique, quaerat facilis sint harum aspernatur sed
          laborum vero quasi quas praesentium nemo deleniti ad quod repudiandae
          corporis. Nihil animi, laborum magnam impedit recusandae reprehenderit
          doloremque est? Optio non obcaecati tenetur voluptas cumque magni
          repellat, corporis culpa nemo error quis perferendis reiciendis
          consequuntur temporibus quaerat magnam, aperiam sit animi. Dolor
          tempora beatae unde distinctio, maiores sequi temporibus obcaecati
          blanditiis architecto esse expedita qui tenetur vel atque commodi
          ducimus at iusto ab amet earum! Voluptates libero soluta odit sapiente
          temporibus, molestias provident facilis non magnam dignissimos quod
          quaerat, debitis nisi architecto tempora repudiandae? Magni deleniti
          laborum, excepturi sit laboriosam qui sint cumque mollitia accusamus
          recusandae pariatur doloremque velit voluptatem vero est voluptatum
          similique tempore aperiam cum voluptatibus, delectus ullam expedita
          quisquam sequi! Eos asperiores sunt aliquam eaque quod eligendi illo
          blanditiis omnis quisquam, debitis aliquid ipsa, totam ducimus, optio
          voluptate repellat ratione officia. Deleniti, recusandae. Iure impedit
          repudiandae magnam commodi voluptas minus sequi corrupti vero quod?
        </div>
      </div>
    </>
  );
}
