import Head from 'next/head'
import Image from "next/image";

const news = [
  { name: "1", href: "#", current: false },
  { name: "2", href: "#", current: false },
  { name: "3", href: "#", current: false },
  { name: "4", href: "#", current: false },

];

export default function Home() {
  return (
    < >
      <Head>
        <title>Kempinski Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-red-500 h-auto fixed">
        <video
          loop autoPlay muted
          className=" min-h-[50%] min-w-[50%] w-auto h-auto -z-10 top-0 "
        >
          <source
            src="/Kempinski-Hotel.mp4"
            type="video/mp4"
          />
        </video>
      </div>

      <div className=' min-h-screen h-auto relative top-[15vh] sm:top-[25vh] md:top-[35vh] lg:top-[40vh]'>
        <div className=' h-full w-full flex flex-col  flex-nowrap text-center p-4 space-y-3 '>
          <span className='text-white font-bold text-xl'> News </span>
          <div className='bg-white h-36 rounded-lg items-center flex justify-center'>
            fffff
          </div>

        </div>
        <div className=' h-full w-full flex flex-col  flex-nowrap text-center p-4 space-y-3 '>
          <span className='text-white font-bold text-xl'> Aviable </span>
          <div className='bg-white h-36 rounded-lg items-center flex justify-center'>
            fffff
          </div>

        </div>
        <div className=' h-full w-full flex flex-col  flex-nowrap text-center p-4 space-y-3 '>
          <span className='text-white font-bold text-xl'> 33333 </span>
          <div className='bg-white h-36 rounded-lg items-center flex justify-center'>
            fffff
          </div>

        </div>
        <div className=' h-full w-full flex flex-col  flex-nowrap text-center p-4 space-y-3 '>
          <span className='text-white font-bold text-xl'> 44444 </span>
          <div className='bg-white h-36 rounded-lg items-center flex justify-center'>
            fffff
          </div>

        </div>
      </div>
    </>
  )
}
